import React from 'react'
import Head from 'next/head'

const HomeIndex = () => {
  return (
    <React.Fragment>
      <Head>
        <title>React Developer Technical | Kelvin Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </React.Fragment>
  )
}

export default HomeIndex
